baseURL = "https://tintapertinente-dev.netlify.app"
languageCode = "en-us"
title = "Tinta Pertinente"
theme = "ananke"
enableRobotsTXT = true
paginate = 4 # Set the number of posts to show before overflowing to the next page.
summaryLength = 10 # Configure how long the post summary should be on the homepage.
ignoreErrors = ["error-remote-getjson"]